Feature: PublicationCucumber
Generated by Yest

Background: Init PublicationCucumber


Scenario: Döner zubereiten

When Der Kunde das Produkt Döner bestellt
Then Wird mit der Zubereitung von Döner begonnen


Scenario: Dürum zubereiten

When Der Kunde das Produkt Dürum bestellt
Then Wird mit der Zubereitung von Dürum begonnen


Scenario: Lahmacun zubereiten

When Der Kunde das Produkt Lahmacun bestellt
Then Wird mit der Zubereitung von Lahmacun begonnen


