Feature: PublicationCucumber
Generated by Yest

Background: Init PublicationCucumber


Scenario Outline:Döner-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Döner-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Döner
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Döner-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Döner
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Döner-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Döner
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Döner-Falafel-Salat-Rotkohl-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Döner-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Döner-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Döner-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Döner-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Döner-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Döner-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Döner-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Döner-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Döner
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Döner-Kalb-Mild

When customer chooses Döner
 And customer chooses Kalb as main ingredient
 And customer wants nichts Scharfes
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Döner-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Döner-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Döner
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Döner-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Döner
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Döner-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Döner
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Döner-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Döner
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Döner-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Döner
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Döner-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Döner
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Döner-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Döner
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Dürüm-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Dürüm-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Dürüm-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Dürum
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Dürüm-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Dürüm-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Dürüm-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Dürüm-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Dürüm-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Dürüm-Hähnchen-Tomaten-ExtraScharf

When customer chooses Dürum
 And customer chooses Hähnchen as main ingredient
 And customer wants tomatoes
 And customer wants Extra viel Scharf
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Dürüm-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Dürüm-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Dürüm-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Dürüm-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Dürüm-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Dürüm-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Dürüm-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Dürum
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Dürüm-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Dürum
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Dürüm-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Dürüm-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Dürum
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Dürüm-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Dürum
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Dürüm-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Dürum
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Dürüm-Ohne-Salat-Rotkohl-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Dürum
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 5,50 	|


Scenario Outline:Lahmacun-Falafel-Rotkohl-Mild

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants red cabbage
 And customer wants nichts Scharfes
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Rotkohl-Tomaten-ExtraScharf

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants Extra viel Scharf
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Rotkohl-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants red cabbage
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-ExtraScharf

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants Extra viel Scharf
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Tomaten-Mild

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants tomatoes
 And customer wants nichts Scharfes
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Salat-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Salat-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants salad
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,50 	|


Scenario Outline:Lahmacun-Falafel-Tomaten-Weißkohl-Mild

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Falafel-Weißkohl-ExtraScharf

When customer chooses Lahmacun
 And customer chooses Falafel as main ingredient
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra ohne Extras
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 7,00 	|


Scenario Outline:Lahmacun-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Lahmacun-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Lahmacun-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Lahmacun-Hähnchen-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,00 	|


Scenario Outline:Lahmacun-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,50 	|


Scenario Outline:Lahmacun-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,50 	|


Scenario Outline:Lahmacun-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,50 	|


Scenario Outline:Lahmacun-HähnchenKalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,50 	|


Scenario Outline:Lahmacun-HähnchenKalb-Salat-Rotkohl-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Hähnchen & Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 8,50 	|


Scenario Outline:Lahmacun-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 9,00 	|


Scenario Outline:Lahmacun-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 9,00 	|


Scenario Outline:Lahmacun-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Lahmacun
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 9,00 	|


Scenario Outline:Lahmacun-Kalb-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer chooses Kalb as main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 9,00 	|


Scenario Outline:Lahmacun-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-BisschenScharf-Weichkäse

When customer chooses Lahmacun
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Bisschen Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Lahmacun-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-ExtraScharf-Weichkäse

When customer chooses Lahmacun
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Extra viel Scharf
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Lahmacun-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-Mild-Weichkäse

When customer chooses Lahmacun
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants nichts Scharfes
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


Scenario Outline:Lahmacun-Ohne-Salat-Rotkohl-Tomaten-Weißkohl-SosseScharf-Weichkäse

When customer chooses Lahmacun
 And customer does not want any main ingredient
 And customer wants salad
 And customer wants red cabbage
 And customer wants tomatoes
 And customer wants white cabbage
 And customer wants Scharfe Sosse
 And customer wants extra Weichkäse
Then customer has to pay <Preis> EUR

Examples: 
	| Preis	|
	| 6,50 	|


